spring:
  cloud:
    stream:
      bindings:
        input:
          destination: ${INTPUT_CHANNEL}
          group: soundbitsGroup
        soundbitsChannel:
          destination: ${OUTPUT_CHANNEL}

  zipkin:
    enabled: true
    base-url: http://localhost:9411/
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1.0

  application:
    name: subscriber-publisher

logging:
  level:
    org.springframework: info
---
spring:
  profiles:
    active: k8s
  rabbitmq:
    host: rabbitmq

  zipkin:
    base-url: http://zipkin:9411/