reports:
  dir: /Users/ashumilov/projects/syncrhony/gatling-runner/target/reports/
  location: file:${reports.dir}
server:
  port: 8081

spring:
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1.0
---

spring:
  profiles: cloud

reports:
  dir: /home/vcap/app/reports/
  location: file:${reports.dir}
