apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    run: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-manage
spec:
  ports:
  - port: 15672
    protocol: TCP
    targetPort: 15672
    nodePort: 31672    
  selector:
    run: rabbitmq
  type: NodePort  
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: rabbitmq
  name: rabbitmq
spec:
  containers:
  - image: rabbitmq:management
    name: rabbitmq
    ports:
    - containerPort: 5672
    - containerPort: 15672  