spring:
  cloud:
    stream:
      bindings:
        input:
          destination: ${INPUT_CHANNEL}
          group: soundbitsGroup
        responseChannel:
          destination: response-channel
  zipkin:
    enabled: false
    base-url: http://localhost:9411/
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1.0

  application:
    name: subscriber

http-listener:
  url: http://localhost:8383

---
spring:
  profiles: k8s
  rabbitmq:
    host: rabbitmq

  zipkin:
    base-url: http://zipkin:9411/

http-listener:
  url: http://http-listener:8080